=== ZacharyWesterman/gigawidgets/tools/xmltree/gigawidgets.dtd
<!-- 
    DTD for GigaWidgets XML Parser
    Defines all valid XML elements and attributes supported by the xmltree parser
    Generated from parser analysis
-->

<!-- Root element: exactly one widget -->
<!ELEMENT body (collection | column | row | panel | blink | text | input | image)>
<!ATTLIST body
    color CDATA #IMPLIED
    rotation (0 | 90 | 180 | 270) #IMPLIED
    padding CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Container: Collection - can contain any widgets -->
<!ELEMENT collection (collection | column | row | panel | blink | text | input | image)*>
<!ATTLIST collection
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
    size CDATA #REQUIRED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Container: Column - can contain any widgets -->
<!ELEMENT column (collection | column | row | panel | blink | text | input | image)*>
<!ATTLIST column
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
    size CDATA #REQUIRED
    order (top | bottom | top-down | bottom-up) #IMPLIED
    height CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Container: Row - can contain any widgets -->
<!ELEMENT row (collection | column | row | panel | blink | text | input | image)*>
<!ATTLIST row
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
    size CDATA #REQUIRED
    order (left | right | left-to-right | right-to-left) #IMPLIED
    width CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Container: Panel - exactly one child widget with background -->
<!ELEMENT panel (collection | column | row | panel | blink | text | input | image)>
<!ATTLIST panel
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
    color CDATA #IMPLIED
    size CDATA #IMPLIED
    radius CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Container: Blink - exactly one child widget with blinking animation -->
<!ELEMENT blink (collection | column | row | panel | blink | text | input | image)>
<!ATTLIST blink
    time CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Leaf: Text - displays text content, no children allowed -->
<!ELEMENT text (#PCDATA)>
<!ATTLIST text
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
    font (FreeMono9pt7b | FreeMono12pt7b | FreeMono18pt7b | FreeMono24pt7b |
          FreeMonoBold9pt7b | FreeMonoBold12pt7b | FreeMonoBold18pt7b | FreeMonoBold24pt7b |
          FreeMonoBoldOblique9pt7b | FreeMonoBoldOblique12pt7b | FreeMonoBoldOblique18pt7b | FreeMonoBoldOblique24pt7b |
          FreeMonoOblique9pt7b | FreeMonoOblique12pt7b | FreeMonoOblique18pt7b | FreeMonoOblique24pt7b |
          FreeSans9pt7b | FreeSans12pt7b | FreeSans18pt7b | FreeSans24pt7b |
          FreeSansBold9pt7b | FreeSansBold12pt7b | FreeSansBold18pt7b | FreeSansBold24pt7b |
          FreeSansBoldOblique9pt7b | FreeSansBoldOblique12pt7b | FreeSansBoldOblique18pt7b | FreeSansBoldOblique24pt7b |
          FreeSansOblique9pt7b | FreeSansOblique12pt7b | FreeSansOblique18pt7b | FreeSansOblique24pt7b |
          FreeSerif9pt7b | FreeSerif12pt7b | FreeSerif18pt7b | FreeSerif24pt7b |
          FreeSerifBold9pt7b | FreeSerifBold12pt7b | FreeSerifBold18pt7b | FreeSerifBold24pt7b |
          FreeSerifBoldItalic9pt7b | FreeSerifBoldItalic12pt7b | FreeSerifBoldItalic18pt7b | FreeSerifBoldItalic24pt7b |
          FreeSerifItalic9pt7b | FreeSerifItalic12pt7b | FreeSerifItalic18pt7b | FreeSerifItalic24pt7b |
          Org_01 | Picopixel | Tiny3x3a2pt7b | TomThumb) #IMPLIED
    scale CDATA #IMPLIED
    color CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Leaf: Input - text input field, no children allowed -->
<!ELEMENT input EMPTY>
<!ATTLIST input
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    padding CDATA #IMPLIED
    size CDATA #IMPLIED
    radius CDATA #IMPLIED
    font (FreeMono9pt7b | FreeMono12pt7b | FreeMono18pt7b | FreeMono24pt7b |
          FreeMonoBold9pt7b | FreeMonoBold12pt7b | FreeMonoBold18pt7b | FreeMonoBold24pt7b |
          FreeMonoBoldOblique9pt7b | FreeMonoBoldOblique12pt7b | FreeMonoBoldOblique18pt7b | FreeMonoBoldOblique24pt7b |
          FreeMonoOblique9pt7b | FreeMonoOblique12pt7b | FreeMonoOblique18pt7b | FreeMonoOblique24pt7b |
          FreeSans9pt7b | FreeSans12pt7b | FreeSans18pt7b | FreeSans24pt7b |
          FreeSansBold9pt7b | FreeSansBold12pt7b | FreeSansBold18pt7b | FreeSansBold24pt7b |
          FreeSansBoldOblique9pt7b | FreeSansBoldOblique12pt7b | FreeSansBoldOblique18pt7b | FreeSansBoldOblique24pt7b |
          FreeSansOblique9pt7b | FreeSansOblique12pt7b | FreeSansOblique18pt7b | FreeSansOblique24pt7b |
          FreeSerif9pt7b | FreeSerif12pt7b | FreeSerif18pt7b | FreeSerif24pt7b |
          FreeSerifBold9pt7b | FreeSerifBold12pt7b | FreeSerifBold18pt7b | FreeSerifBold24pt7b |
          FreeSerifBoldItalic9pt7b | FreeSerifBoldItalic12pt7b | FreeSerifBoldItalic18pt7b | FreeSerifBoldItalic24pt7b |
          FreeSerifItalic9pt7b | FreeSerifItalic12pt7b | FreeSerifItalic18pt7b | FreeSerifItalic24pt7b |
          Org_01 | Picopixel | Tiny3x3a2pt7b | TomThumb) #IMPLIED
    scale CDATA #IMPLIED
    color CDATA #IMPLIED
    text-color CDATA #IMPLIED
    value CDATA #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- Leaf: Image - displays an image/icon, no children allowed -->
<!ELEMENT image EMPTY>
<!ATTLIST image
    pos CDATA #IMPLIED
    align CDATA #IMPLIED
    source CDATA #REQUIRED
    shader (grayscale | halfGrayscaleV | negative | glow | startupRainbow) #IMPLIED
    class CDATA #IMPLIED
    onclick CDATA #IMPLIED
    onblur CDATA #IMPLIED
    onpress CDATA #IMPLIED
    onrelease CDATA #IMPLIED
    onhold CDATA #IMPLIED
>

<!-- 
    ATTRIBUTE VALUE FORMATS:
    
    color: Named colors (white, black, red, green, blue, etc.) or hex format (#RGB or #RRGGBB)
           Valid named colors: white, black, gray, red, orange, yellow, green, cyan, blue, purple, magenta, 
                               light-gray, light-red, light-orange, light-yellow, light-green, light-cyan, 
                               light-blue, pink
    
    pos/align: Space-separated pair of Position values (numeric -1.0 to 1.0) or alignment keywords
               Alignment: "left|center|right top|center|bottom"
    
    size: Numeric value with unit (px, vw, vh, in, cm, mm) or just numeric (defaults to px)
          Examples: "100px", "50", "10cm", "5in"
    
    padding: 1, 2, or 4 space-separated size values
             Examples: "10", "10 20", "10 20 30 40"
    
    scale: Integer scale factor for text size
    
    time: Number with time unit (ms, milli, s, sec, m, min, h, hr, d, dy, days)
          Examples: "500ms", "1s", "30sec", "2min", "1hr"
    
    value: String text content for input elements
    
    rotation: 0, 90, 180, or 270 degrees
    
    order: Vertical ordering (TOP, BOTTOM, TOP-DOWN, BOTTOM-UP)
           Horizontal ordering (LEFT, RIGHT, LEFT-TO-RIGHT, RIGHT-TO-LEFT)
    
    class: Space-separated list of CSS class names for styling
-->

=== ZacharyWesterman/gigawidgets/examples/fonts.xml
<?xml version="1.0"?>
<!DOCTYPE body SYSTEM "../tools/xmltree/gigawidgets.dtd">
<body>
    <column size="100vw 100vh">
        <text scale="2" color="#b09090">Fonts available in 9, 12, 18, and 24 pt:</text>
        <text font="FreeMono9pt7b">FreeMono9pt7b</text>
        <text font="FreeMonoBold9pt7b">FreeMonoBold9pt7b</text>
        <text font="FreeMonoBoldOblique9pt7b">FreeMonoBoldOblique9pt7b</text>
        <text font="FreeMonoOblique9pt7b">FreeMonoOblique9pt7b</text>
        <text font="FreeSans9pt7b">FreeSans9pt7b</text>
        <text font="FreeSansBold9pt7b">FreeSansBold9pt7b</text>
        <text font="FreeSansBoldOblique9pt7b">FreeSansBoldOblique9pt7b</text>
        <text font="FreeSansOblique9pt7b">FreeSansOblique9pt7b</text>
        <text font="FreeSerif9pt7b">FreeSerif9pt7b</text>
        <text font="FreeSerifBold9pt7b">FreeSerifBold9pt7b</text>
        <text font="FreeSerifBoldItalic9pt7b">FreeSerifBoldItalic9pt7b</text>
        <text font="FreeSerifItalic9pt7b">FreeSerifItalic9pt7b</text>

        <text scale="2" color="#b09090">Tiny fonts:</text>
        <text font="Org_01">Org_01</text>
        <text font="Picopixel">Picopixel</text>
        <text font="Tiny3x3a2pt7b">Tiny3x3a2pt7b</text>
        <text font="TomThumb">TomThumb</text>
    </column>
</body>

=== ZacharyWesterman/gigawidgets/examples/player/player.xml
<?xml version="1.0"?>
<!DOCTYPE body SYSTEM "../../tools/xmltree/gigawidgets.dtd">
<body color="#254" rotation="90">
    <column size="100vh 100vw">
        <row size="100vh 75vw">
            <!-- Album Art -->
            <panel size="50vh 75vw" color="#4a8">
                <image align="center center" source="image" />
            </panel>
            <!-- Song/Artist/Album details -->
            <column size="50vh 30vw" align="right center" padding="0.2cm 0">
                <text font="FreeSerifBold24pt7b">Song Name</text>
                <text font="FreeSerif18pt7b">Album Name</text>
                <text font="FreeSerif18pt7b">Artist Name</text>
                <text font="FreeSerif18pt7b">1/20</text>
                <text id="status" font="FreeSerif18pt7b" color="gray">Paused</text>
            </column>
        </row>

        <!-- Controls -->
        <panel size="100vh 25vw" color="#386">
            <row size="69vh 25vw" padding="5px" align="center center">
                <image source="backward_fast" onpress="mark" onrelease="unmark" />
                <image source="backward" onpress="mark" onrelease="unmark" />
                <image source="play" onpress="mark" onrelease="toggle_player" />
                <image source="forward" onpress="mark" onrelease="unmark" />
                <image source="forward_fast" onpress="mark" onrelease="unmark" />
            </row>
        </panel>
    </column>
</body>
